### ISSUE TITLE
issues with test, swap var for let

### ISSUE THREAD

**Issue by jonalexander** [learn-co-curriculum/javascript-hide-and-seek#2]
tests weren't working. removed 'let' from the variable declarations and replaced with 'var'. tests worked.

error message:

> java-script-hide-and-seek@0.1.0 test /Users/jonalexander/Development/code/javascript-hide-and-seek-web-0616
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

/Users/jonalexander/Development/code/javascript-hide-and-seek-web-0616/test/index-test.js:40
      let children = firstList.children
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/jonalexander/Development/code/javascript-hide-and-seek-web-0616/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/jonalexander/Development/code/javascript-hide-and-seek-web-0616/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/jonalexander/Development/code/javascript-hide-and-seek-web-0616/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/jonalexander/Development/code/javascript-hide-and-seek-web-0616/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
npm ERR! Test failed.  See above for more details.
/Users/jonalexander/.rvm/gems/ruby-2.2.3/gems/learn-test-2.4.0/lib/learn_test/strategies/mocha.rb:49:in `results': undefined method`[]' for nil:NilClass (NoMethodError)
    from /Users/jonalexander/.rvm/gems/ruby-2.2.3/gems/learn-test-2.4.0/lib/learn_test/runner.rb:68:in `push_results'
    from /Users/jonalexander/.rvm/gems/ruby-2.2.3/gems/learn-test-2.4.0/lib/learn_test/runner.rb:19:in`run'
    from /Users/jonalexander/.rvm/gems/ruby-2.2.3/gems/learn-test-2.4.0/bin/learn-test:60:in `<top (required)>'
    from /Users/jonalexander/.rvm/gems/ruby-2.2.3/bin/learn-test:22:in`load'
    from /Users/jonalexander/.rvm/gems/ruby-2.2.3/bin/learn-test:22:in `<main>'
    from /Users/jonalexander/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in`eval'
    from /Users/jonalexander/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by pletcher** [comment]
Please update the version of Node that you're using.
